name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
        
    - name: 📂 Deploy with SFTP
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: lx5.hoststar.hosting
        port: 5544
        username: admin.zelemu.com
        password: ${{ secrets.FTP_PASSWORD }}
        localPath: './dist/'
        remotePath: './cereo.ai/public_html/'
        forceUpload: true