name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
        
    - name: 📂 List build output
      run: ls -la dist/

    - name: 📂 Deploy via SFTP
      uses: nogsantos/scp-deploy@master
      with:
        src: ./dist/*
        host: lx5.hoststar.hosting
        port: 5544
        user: admin.zelemu.com
        password: ${{ secrets.FTP_PASSWORD }}
        remote: cereo.ai/public_html/