name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: lx5.hoststar.hosting
        username: admin.zelemu.com
        password: ${{ secrets.FTP_PASSWORD }}
        port: 5544
        local_path: './dist/*'
        remote_path: './cereo.ai/public_html/'
        sftp_only: true